logging:
  level:
    org.springframework.security: DEBUG

app:
  jwt:
    secret: fWGy30lAyaSNRLLDq2Lau0LJHkruRPjYem1Jpnt3Q+c=
    expiration-time: 86400000
spring:
  datasource:
    url: jdbc:postgresql://db:5432/supportdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true